// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKiD-PbvwpnL7s_Pj8qUjoAT5u-G3bb8A',
    appId: '1:759114737207:web:b5a4bcd40bd5aa3cf7c1b2',
    messagingSenderId: '759114737207',
    projectId: 'forestapp-889ca',
    authDomain: 'forestapp-889ca.firebaseapp.com',
    storageBucket: 'forestapp-889ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb46A2E0uQBd5R3AvOJDkINoP8fPBTaW0',
    appId: '1:759114737207:android:bc4f819723e4d3f7f7c1b2',
    messagingSenderId: '759114737207',
    projectId: 'forestapp-889ca',
    storageBucket: 'forestapp-889ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDq__TycKRHbwvviXYhnfPGJyxEatd8aM',
    appId: '1:759114737207:ios:0be2dbf45d8e9bbbf7c1b2',
    messagingSenderId: '759114737207',
    projectId: 'forestapp-889ca',
    storageBucket: 'forestapp-889ca.appspot.com',
    iosClientId: '759114737207-3mu17sd1ovdtmg9jh8g9svm96p6qtcrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.forestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDq__TycKRHbwvviXYhnfPGJyxEatd8aM',
    appId: '1:759114737207:ios:0be2dbf45d8e9bbbf7c1b2',
    messagingSenderId: '759114737207',
    projectId: 'forestapp-889ca',
    storageBucket: 'forestapp-889ca.appspot.com',
    iosClientId: '759114737207-3mu17sd1ovdtmg9jh8g9svm96p6qtcrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.forestapp',
  );
}
