// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1eOOA3PUPweuob4XwfzR5DE-_XByhvA4',
    appId: '1:716226720902:web:dd1f1d7e60e0c7e9ab0d07',
    messagingSenderId: '716226720902',
    projectId: 'pench-app',
    authDomain: 'pench-app.firebaseapp.com',
    storageBucket: 'pench-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmAcGCWIfT0j1NCCgjeD6yt-mwbthB1KY',
    appId: '1:716226720902:android:94710978d6024539ab0d07',
    messagingSenderId: '716226720902',
    projectId: 'pench-app',
    storageBucket: 'pench-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4AJNdZNsq9HU3JFPKkKWk7OSpughvmgI',
    appId: '1:716226720902:ios:c6e32d2aa0e61381ab0d07',
    messagingSenderId: '716226720902',
    projectId: 'pench-app',
    storageBucket: 'pench-app.appspot.com',
    iosClientId: '716226720902-5kjalis9kq1enfil35aeg2e911j37sto.apps.googleusercontent.com',
    iosBundleId: 'com.example.forestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4AJNdZNsq9HU3JFPKkKWk7OSpughvmgI',
    appId: '1:716226720902:ios:c6e32d2aa0e61381ab0d07',
    messagingSenderId: '716226720902',
    projectId: 'pench-app',
    storageBucket: 'pench-app.appspot.com',
    iosClientId: '716226720902-5kjalis9kq1enfil35aeg2e911j37sto.apps.googleusercontent.com',
    iosBundleId: 'com.example.forestapp',
  );
}
