// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKoXEjoTVh_TBdGiCdVTU-RqMFamHpEXI',
    appId: '1:464886748295:web:a54f4e551a04bee4d9d422',
    messagingSenderId: '464886748295',
    projectId: 'conflict-pench-firebase',
    authDomain: 'conflict-pench-firebase.firebaseapp.com',
    storageBucket: 'conflict-pench-firebase.appspot.com',
    measurementId: 'G-KFB7FS6766',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6o_0Iw1JfXRa609AxOihNJonlMg_LyA',
    appId: '1:464886748295:android:7c885928f097ece0d9d422',
    messagingSenderId: '464886748295',
    projectId: 'conflict-pench-firebase',
    storageBucket: 'conflict-pench-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Iay2pXuA3Jv3EshLLq1iChGqtWyTHfE',
    appId: '1:464886748295:ios:97aff4bfde7527aad9d422',
    messagingSenderId: '464886748295',
    projectId: 'conflict-pench-firebase',
    storageBucket: 'conflict-pench-firebase.appspot.com',
    iosBundleId: 'com.example.forestapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Iay2pXuA3Jv3EshLLq1iChGqtWyTHfE',
    appId: '1:464886748295:ios:97aff4bfde7527aad9d422',
    messagingSenderId: '464886748295',
    projectId: 'conflict-pench-firebase',
    storageBucket: 'conflict-pench-firebase.appspot.com',
    iosBundleId: 'com.example.forestapp1',
  );
}
