var user = 1;
var admin = -1;
var noOne = 0;

var SHARED_USER_TYPE = "SHARED_USER_TYPE";
var SHARED_USER_EMAIL = "SHARED_USER_EMAIL";
var SHARED_USER_LATITUDE = "SHARED_USER_LATITUDE";
var SHARED_USER_LONGITUDE = "SHARED_USER_LONGITUDE";
var SHARED_USER_RADIUS = "SHARED_USER_RADIUS";
var SHARED_USER_NAME = "SHARED_USER_NAME";
var SHARED_USER_CONTACT = "SHARED_USER_CONTACT";
var SHARED_USER_IMAGEURL = "SHARED_USER_IMAGEURL";